### Ques 4.1. To perform Term-Frequency Analysis and Named Entity Recognition on a given text using any toolkit.
**Calculate the frequency of each word and save the output in CSV format (Term, Frequency)**

In [2]:
import re
from collections import Counter
import pandas as pd
import spacy
import string

# 1. Read file and calculate term frequency
file_path = "4.1_4.2_input.txt"
with open(file_path, "r", encoding="utf-8") as f:
    text = f.read()

words = re.findall(r"\b\w+\b", text.lower())
word_counts = Counter(words)

**Explanation:**
In this section, we calculate the term frequency by tokenizing the text and using `collections.Counter`. The results are saved into a CSV file.

**Identify the top 10 most frequent terms and display their corresponding frequencies.**

In [18]:
df_tf = pd.DataFrame(word_counts.items(), columns=["Term", "Frequency"])
df_tf = df_tf.sort_values(by="Frequency", ascending=False).reset_index(drop=True)
df_tf.to_csv("term_frequencies.csv", index=False)

top_10 = df_tf.head(10)
print("=== Top 10 Most Frequent Terms ===")
print(top_10.to_string(index=False))

=== Top 10 Most Frequent Terms ===
Term  Frequency
   a         90
 and         86
 the         75
  in         42
  to         42
  of         42
 can         41
  is         37
word         30
 may         30

**Explanation:**
We sort the term frequencies in descending order and extract the top 10 most frequent terms using a pandas DataFrame.

**Perform Named Entity Recognition and display the entities found.**

In [4]:
import pandas as pd
nlp = spacy.load("en_core_web_sm")
doc = nlp(text)

df_ner = pd.DataFrame(
    [(ent.text, ent.label_, spacy.explain(ent.label_)) for ent in doc.ents],
    columns=["Entity", "Label", "Description"]
)

print(f"Total named entities found: {len(doc.ents)}")
df_ner.head(20)

Total named entities found: 66

,Entity,Label,Description
0,Natural Language Processing and Artificial Int...,ORG,"Companies, agencies, institutions, etc."
1,NLP,ORG,"Companies, agencies, institutions, etc."
2,English,LANGUAGE,Any named language
3,Hindi,GPE,"Countries, cities, states"
4,Assamese,NORP,Nationalities or religious or political groups
5,Bengali,NORP,Nationalities or religious or political groups
6,Tamil,GPE,"Countries, cities, states"
7,NLP,ORG,"Companies, agencies, institutions, etc."
8,NLP,ORG,"Companies, agencies, institutions, etc."
9,NLP,ORG,"Companies, agencies, institutions, etc."
10,twenty,CARDINAL,Numerals that do not fall under another type
11,twenty,DATE,Absolute or relative dates or periods
12,Python,GPE,"Countries, cities, states"
13,First,ORDINAL,"""first"", ""second"", etc."
14,first,ORDINAL,"""first"", ""second"", etc."
15,thousands,CARDINAL,Numerals that do not fall under another type
16,hundreds or thousands,CARDINAL,Numerals that do not fall under another type
17,twenty,CARDINAL,Numerals that do not fall under another type
18,One,CARDINAL,Numerals that do not fall under another type
19,Term Frequency-Inverse Document Frequency,ORG,"Companies, agencies, institutions, etc."

**Explanation:**
We use the spaCy library with the `en_core_web_sm` model to extract named entities from the text and categorize them by their labels.

In [5]:
ner_counts = Counter(ent.label_ for ent in doc.ents)
print("=== Named Entity Count by Type ===")
for label, count in ner_counts.most_common():
    print(f"{label:10} {count:4} {spacy.explain(label)}")

=== Named Entity Count by Type ===
ORG          31 Companies, agencies, institutions, etc.
CARDINAL     13 Numerals that do not fall under another type
PERSON        7 People, including fictional
GPE           6 Countries, cities, states
LANGUAGE      3 Any named language
NORP          3 Nationalities or religious or political groups
ORDINAL       2 "first", "second", etc.
DATE          1 Absolute or relative dates or periods

### Ques 4.2. To perform Term-Frequency Analysis on a given text without using any toolkit.
**Calculate the frequency of each word and save the output in CSV format (Term, Frequency)**

In [6]:
import pandas as pd
import string
file_path = "4.1_4.2_input.txt"
with open(file_path, "r", encoding="utf-8") as f:
    text = f.read()

split_arr = text.split()
hash_map = dict()

for x in range(len(split_arr)):
    term = split_arr[x].strip(string.punctuation).lower()
    if not term: # token was pure punctuation
        continue
    split_arr[x] = term
    hash_map[term] = hash_map.get(term, 0) + 1

df_tf_2 = pd.DataFrame(hash_map.items(), columns=["Term", "Frequency"])
df_tf_2 = df_tf_2.sort_values(by="Frequency", ascending=False).reset_index(drop=True)
df_tf_2.to_csv("term_frequencies_without_toolkit.csv", index=False)

df_tf_2.head(10)

   Term  Frequency
0     a         90
1   and         86
2   the         75
3    in         42
4    to         42
5   can         41
6    of         40
7    is         37
8   may         30
9  word         30

**Explanation:**
Here, we calculate the term frequencies manually without using external NLP libraries. We split the text, strip punctuation, and count the occurrences using a dictionary.

### Ques 4.3. Write a Python program without using NLTK, spaCy, or any other NLP toolkit to:
**1. Read multiple text documents.**

In [7]:
doc1 = "Natural language processing is a field of artificial intelligence."
doc2 = "Natural language processing helps computers understand human language."
doc3 = "Machine learning is an important part of artificial intelligence."

docs = [doc1, doc2, doc3]

**Explanation:**
We start by initializing the given text documents into a list.

**2. Convert text to lowercase.**

In [8]:
docs_lower = [d.lower() for d in docs]
docs_lower

['natural language processing is a field of artificial intelligence.',
 'natural language processing helps computers understand human language.',
 'machine learning is an important part of artificial intelligence.']

**Explanation:**
We iterate through the documents and convert all characters to lowercase to maintain consistency.

**3. Remove punctuation.**

In [9]:
import string
translator = str.maketrans("", "", string.punctuation)
docs_nopunct = [d.translate(translator) for d in docs_lower]
docs_nopunct

['natural language processing is a field of artificial intelligence',
 'natural language processing helps computers understand human language',
 'machine learning is an important part of artificial intelligence']

**Explanation:**
We use the `str.translate` method with `string.punctuation` to remove all punctuation marks from the documents.

**4. Tokenize the documents.**

In [10]:
tokenized_docs = [[tok for tok in d.split() if tok] for d in docs_nopunct]
for i in range(len(tokenized_docs)):
    print(f"Doc{i + 1} ({len(tokenized_docs[i])} tokens): {tokenized_docs[i]}")

Doc1 (9 tokens): ['natural', 'language', 'processing', 'is', 'a', 'field', 'of', 'artificial', 'intelligence']
Doc2 (8 tokens): ['natural', 'language', 'processing', 'helps', 'computers', 'understand', 'human', 'language']
Doc3 (9 tokens): ['machine', 'learning', 'is', 'an', 'important', 'part', 'of', 'artificial', 'intelligence']

**Explanation:**
The text is split by whitespace to create a list of words (tokens) for each document.

**5. Calculate TF for every term.**

In [11]:
import pandas as pd
tf_rows = []
for i in range(len(tokenized_docs)):
    doc_len = len(tokenized_docs[i])
    term_counts = dict()
    
    for token in tokenized_docs[i]:
        term_counts[token] = term_counts.get(token, 0) + 1
        
    for term, count in term_counts.items():
        tf_rows.append((f"Doc{i + 1}", term, count, doc_len, count / doc_len))

df_tf_docs = pd.DataFrame(
    tf_rows, columns=["Document", "Term", "Count", "DocLength", "TF"]
)
df_tf_docs

   Document          Term  Count  DocLength        TF
0      Doc1       natural      1          9  0.111111
1      Doc1      language      1          9  0.111111
2      Doc1    processing      1          9  0.111111
3      Doc1            is      1          9  0.111111
4      Doc1             a      1          9  0.111111
5      Doc1         field      1          9  0.111111
6      Doc1            of      1          9  0.111111
7      Doc1    artificial      1          9  0.111111
8      Doc1  intelligence      1          9  0.111111
9      Doc2       natural      1          8  0.125000
10     Doc2      language      2          8  0.250000
11     Doc2    processing      1          8  0.125000
12     Doc2         helps      1          8  0.125000
13     Doc2     computers      1          8  0.125000
14     Doc2    understand      1          8  0.125000
15     Doc2         human      1          8  0.125000
16     Doc3       machine      1          9  0.111111
17     Doc3      learning      1          9  0.111111
18     Doc3            is      1          9  0.111111
19     Doc3            an      1          9  0.111111
20     Doc3     important      1          9  0.111111
21     Doc3          part      1          9  0.111111
22     Doc3            of      1          9  0.111111
23     Doc3    artificial      1          9  0.111111
24     Doc3  intelligence      1          9  0.111111

**Explanation:**
Term Frequency (TF) is calculated as the count of a term in a document divided by the total number of words in that document.

In [12]:
import pandas as pd
import math
df_counts = dict()

for tokens in tokenized_docs:
    unique_terms = set(tokens)
    for term in unique_terms:
        df_counts[term] = df_counts.get(term, 0) + 1

df_df = (
    pd.DataFrame(df_counts.items(), columns=["Term", "DF"])
    .sort_values("Term")
    .reset_index(drop=True)
)
df_df

            Term  DF
0              a   1
1             an   1
2     artificial   2
3      computers   1
4          field   1
5          helps   1
6          human   1
7      important   1
8   intelligence   2
9             is   2
10      language   2
11      learning   1
12       machine   1
13       natural   2
14            of   2
15          part   1
16    processing   2
17    understand   1

**7. Calculate IDF using the logarithmic formula.**

In [13]:
num_docs = len(tokenized_docs)
df_df["IDF"] = df_df["DF"].apply(lambda d: math.log(num_docs / d))
df_df

            Term  DF       IDF
0              a   1  1.098612
1             an   1  1.098612
2     artificial   2  0.405465
3      computers   1  1.098612
4          field   1  1.098612
5          helps   1  1.098612
6          human   1  1.098612
7      important   1  1.098612
8   intelligence   2  0.405465
9             is   2  0.405465
10      language   2  0.405465
11      learning   1  1.098612
12       machine   1  1.098612
13       natural   2  0.405465
14            of   2  0.405465
15          part   1  1.098612
16    processing   2  0.405465
17    understand   1  1.098612

**Explanation:**
Inverse Document Frequency (IDF) is calculated using the formula `log(N / DF)`, where N is the total number of documents.

**8. Calculate TF-IDF for every term in every document.**

In [14]:
df_tfidf = df_tf_docs.merge(df_df, on="Term")
df_tfidf["TF-IDF"] = df_tfidf["TF"] * df_tfidf["IDF"]
df_tfidf

   Document          Term  Count  DocLength        TF  DF       IDF    TF-IDF
0      Doc1       natural      1          9  0.111111   2  0.405465  0.045052
1      Doc1      language      1          9  0.111111   2  0.405465  0.045052
2      Doc1    processing      1          9  0.111111   2  0.405465  0.045052
3      Doc1            is      1          9  0.111111   2  0.405465  0.045052
4      Doc1             a      1          9  0.111111   1  1.098612  0.122068
5      Doc1         field      1          9  0.111111   1  1.098612  0.122068
6      Doc1            of      1          9  0.111111   2  0.405465  0.045052
7      Doc1    artificial      1          9  0.111111   2  0.405465  0.045052
8      Doc1  intelligence      1          9  0.111111   2  0.405465  0.045052
9      Doc2       natural      1          8  0.125000   2  0.405465  0.050683
10     Doc2      language      2          8  0.250000   2  0.405465  0.101366
11     Doc2    processing      1          8  0.125000   2  0.405465  0.050683
12     Doc2         helps      1          8  0.125000   1  1.098612  0.137327
13     Doc2     computers      1          8  0.125000   1  1.098612  0.137327
14     Doc2    understand      1          8  0.125000   1  1.098612  0.137327
15     Doc2         human      1          8  0.125000   1  1.098612  0.137327
16     Doc3       machine      1          9  0.111111   1  1.098612  0.122068
17     Doc3      learning      1          9  0.111111   1  1.098612  0.122068
18     Doc3            is      1          9  0.111111   2  0.405465  0.045052
19     Doc3            an      1          9  0.111111   1  1.098612  0.122068
20     Doc3     important      1          9  0.111111   1  1.098612  0.122068
21     Doc3          part      1          9  0.111111   1  1.098612  0.122068
22     Doc3            of      1          9  0.111111   2  0.405465  0.045052
23     Doc3    artificial      1          9  0.111111   2  0.405465  0.045052
24     Doc3  intelligence      1          9  0.111111   2  0.405465  0.045052

**Explanation:**
The TF-IDF score is the product of Term Frequency (TF) and Inverse Document Frequency (IDF).

**9. Display Term, TF, DF, IDF, and TF-IDF at each step.**

In [15]:
df_display = df_tfidf[["Document", "Term", "TF", "DF", "IDF", "TF-IDF"]]
df_display

   Document          Term        TF  DF       IDF    TF-IDF
0      Doc1       natural  0.111111   2  0.405465  0.045052
1      Doc1      language  0.111111   2  0.405465  0.045052
2      Doc1    processing  0.111111   2  0.405465  0.045052
3      Doc1            is  0.111111   2  0.405465  0.045052
4      Doc1             a  0.111111   1  1.098612  0.122068
5      Doc1         field  0.111111   1  1.098612  0.122068
6      Doc1            of  0.111111   2  0.405465  0.045052
7      Doc1    artificial  0.111111   2  0.405465  0.045052
8      Doc1  intelligence  0.111111   2  0.405465  0.045052
9      Doc2       natural  0.125000   2  0.405465  0.050683
10     Doc2      language  0.250000   2  0.405465  0.101366
11     Doc2    processing  0.125000   2  0.405465  0.050683
12     Doc2         helps  0.125000   1  1.098612  0.137327
13     Doc2     computers  0.125000   1  1.098612  0.137327
14     Doc2    understand  0.125000   1  1.098612  0.137327
15     Doc2         human  0.125000   1  1.098612  0.137327
16     Doc3       machine  0.111111   1  1.098612  0.122068
17     Doc3      learning  0.111111   1  1.098612  0.122068
18     Doc3            is  0.111111   2  0.405465  0.045052
19     Doc3            an  0.111111   1  1.098612  0.122068
20     Doc3     important  0.111111   1  1.098612  0.122068
21     Doc3          part  0.111111   1  1.098612  0.122068
22     Doc3            of  0.111111   2  0.405465  0.045052
23     Doc3    artificial  0.111111   2  0.405465  0.045052
24     Doc3  intelligence  0.111111   2  0.405465  0.045052

**Explanation:**
We format the calculated metrics into a pandas DataFrame for better visualization.

**10. Identify the top 10 terms with the highest TF-IDF score for each document.**

In [16]:
for doc in df_tfidf["Document"].unique():
    top_10_doc = (
        df_tfidf[df_tfidf["Document"] == doc]
        .sort_values(by="TF-IDF", ascending=False)
        .head(10)
        .reset_index(drop=True)
    )
    print(f"=== Top 10 Terms by TF-IDF for {doc} ===")
    print(top_10_doc[["Term", "TF", "DF", "IDF", "TF-IDF"]].to_string(index=False))
    print()

=== Top 10 Terms by TF-IDF for Doc1 ===
        Term       TF  DF      IDF   TF-IDF
           a 0.111111   1 1.098612 0.122068
       field 0.111111   1 1.098612 0.122068
     natural 0.111111   2 0.405465 0.045052
    language 0.111111   2 0.405465 0.045052
  processing 0.111111   2 0.405465 0.045052
          is 0.111111   2 0.405465 0.045052
          of 0.111111   2 0.405465 0.045052
  artificial 0.111111   2 0.405465 0.045052
intelligence 0.111111   2 0.405465 0.045052

=== Top 10 Terms by TF-IDF for Doc2 ===
      Term    TF  DF      IDF   TF-IDF
     helps 0.125   1 1.098612 0.137327
 computers 0.125   1 1.098612 0.137327
understand 0.125   1 1.098612 0.137327
     human 0.125   1 1.098612 0.137327
  language 0.250   2 0.405465 0.101366
   natural 0.125   2 0.405465 0.050683
processing 0.125   2 0.405465 0.050683

=== Top 10 Terms by TF-IDF for Doc3 ===
        Term       TF  DF      IDF   TF-IDF
     machine 0.111111   1 1.098612 0.122068
    learning 0.111111   1 1.098612 0.122068
          an 0.111111   1 1.098612 0.122068
   important 0.111111   1 1.098612 0.122068
        part 0.111111   1 1.098612 0.122068
          is 0.111111   2 0.405465 0.045052
          of 0.111111   2 0.405465 0.045052
  artificial 0.111111   2 0.405465 0.045052
intelligence 0.111111   2 0.405465 0.045052

**Explanation:**
For each document, we sort the terms by their TF-IDF scores in descending order and display the top 10.